import type { CsvPersonRow } from '../types';

export const starterPeople: CsvPersonRow[] = [
  {
    name: 'Satya Nadella',
    headline: 'Chairman and CEO',
    company: 'Microsoft',
    notes: 'Public-company leadership and AI platform strategy.',
  },
  {
    name: 'Taylor Swift',
    headline: 'Singer-songwriter and producer',
    company: 'Entertainment',
    notes: 'Global touring artist with major fan engagement and brand partnerships.',
  },
  {
    name: 'Simone Biles',
    headline: 'Olympic gymnast',
    company: 'Team USA',
    notes: 'Decorated gymnast and mental-health advocate.',
  },
  {
    name: 'Jensen Huang',
    headline: 'President and CEO',
    company: 'NVIDIA',
    notes: 'Known for GPU and AI infrastructure leadership.',
  },
  {
    name: 'Serena Williams',
    headline: 'Former world No. 1 tennis player',
    company: 'Serena Ventures',
    notes: 'Athlete and entrepreneur in beauty and venture investing.',
  },
  {
    name: 'Volodymyr Zelenskyy',
    headline: 'President',
    company: 'Ukraine',
    notes: 'Head of state and frequent international diplomacy figure.',
  },
  {
    name: 'Tim Cook',
    headline: 'Chief Executive Officer',
    company: 'Apple',
    notes: 'Leads Apple product ecosystem and operations strategy.',
  },
  {
    name: 'Megan Rapinoe',
    headline: 'Former professional soccer player',
    company: 'USWNT',
    notes: 'World Cup winner and equality advocate.',
  },
  {
    name: 'Barack Obama',
    headline: '44th President of the United States',
    company: 'Obama Foundation',
    photoUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTeRRXklt4dVsHG4m73r1Bc4y__HB5fcUIDhw&s',
    notes: 'Former US president and author.',
  },
  {
    name: 'Oprah Winfrey',
    headline: 'Media executive and philanthropist',
    company: 'OWN',
    notes: 'Talk show host, producer, and media mogul.',
  },
  {
    name: 'Elon Musk',
    headline: 'CEO',
    company: 'Tesla, SpaceX',
    notes: 'Entrepreneur in EVs, space, and AI.',
  },
  {
    name: 'Beyoncé',
    headline: 'Singer and producer',
    company: 'Parkwood Entertainment',
    notes: 'Grammy-winning artist and businesswoman.',
  },
  {
    name: 'LeBron James',
    headline: 'Professional basketball player',
    company: 'Los Angeles Lakers',
    notes: 'NBA superstar and entrepreneur.',
  },
  {
    name: 'Keanu Reeves',
    headline: 'Actor',
    company: 'Hollywood',
    notes: 'Actor known for The Matrix and John Wick.',
  },
  {
    name: 'Greta Thunberg',
    headline: 'Climate activist',
    company: 'Fridays for Future',
    notes: 'Swedish environmental activist.',
  },
  {
    name: 'Rihanna',
    headline: 'Singer and entrepreneur',
    company: 'Fenty',
    photoUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRiceYLHtIwOGjCDHNwlTgfkg9OeNX1QzECqsHFlXWUqpYKBwsDQDB6MHLgOw5oJUo7pCXplj1YfZq9sbU_o_SD0BWtVHGfla9VDoUTvbM&s=10',
    notes: 'Recording artist and founder of Fenty Beauty.',
  },
  {
    name: 'Cristiano Ronaldo',
    headline: 'Professional footballer',
    company: 'Al Nassr',
    notes: 'Portuguese forward, multi Ballon d\u2019Or winner.',
  },
  {
    name: 'Lionel Messi',
    headline: 'Professional footballer',
    company: 'Inter Miami',
    notes: 'Argentine forward, World Cup winner.',
  },
  {
    name: 'Angela Merkel',
    headline: 'Former Chancellor',
    company: 'Germany',
    photoUrl: 'https://cdn.britannica.com/17/172817-050-B5A3AE9B/Angela-Merkel-2012.jpg',
    notes: 'Long-serving German chancellor.',
  },
  {
    name: 'Bill Gates',
    headline: 'Co-founder',
    company: 'Microsoft / Gates Foundation',
    notes: 'Microsoft co-founder and philanthropist.',
  },
];
